version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        ENV: production
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    env_file:
      - configs/production.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - justlist-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Production Build
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.frontend.prod
      args:
        ENV: production
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=https://your-render-backend.onrender.com
      - REACT_APP_ENV=production
    networks:
      - justlist-network
    depends_on:
      - backend
    restart: always

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    networks:
      - justlist-network
    depends_on:
      - frontend
      - backend
    restart: always

networks:
  justlist-network:
    driver: bridge

volumes:
  data:
  logs:
