[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run src/app.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
