runtime: python39

env_variables:
  GOOGLE_PLACES_API_KEY: "your_google_places_api_key_here"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always
